# Generated by Django 6.0.1 on 2026-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchased', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('price', models.FloatField(default=0.0, verbose_name='Price per Unit')),
            ],
        ),
    ]
